CREATE TABLE IF NOT EXISTS babies (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  user_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS babies_one_per_user
  ON babies (user_id)
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS feeding_sessions (
  id UUID PRIMARY KEY,
  baby_id UUID NOT NULL REFERENCES babies (id) ON DELETE CASCADE,
  started_at TIMESTAMPTZ NOT NULL,
  ended_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS feeding_segments (
  id UUID PRIMARY KEY,
  feeding_session_id UUID NOT NULL REFERENCES feeding_sessions (id) ON DELETE CASCADE,
  side TEXT NOT NULL,
  started_at TIMESTAMPTZ NOT NULL,
  ended_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS bottle_feeds (
  id UUID PRIMARY KEY,
  baby_id UUID NOT NULL REFERENCES babies (id) ON DELETE CASCADE,
  milk_type TEXT NOT NULL,
  amount_ml INTEGER NOT NULL,
  fed_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS diaper_events (
  id UUID PRIMARY KEY,
  baby_id UUID NOT NULL REFERENCES babies (id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS pumping_sessions (
  id UUID PRIMARY KEY,
  baby_id UUID NOT NULL REFERENCES babies (id) ON DELETE CASCADE,
  started_at TIMESTAMPTZ NOT NULL,
  amount_ml INTEGER,
  duration_minutes INTEGER,
  side TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS measurements (
  id UUID PRIMARY KEY,
  baby_id UUID NOT NULL REFERENCES babies (id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  value DOUBLE PRECISION NOT NULL,
  unit TEXT NOT NULL,
  measured_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS reminder_rules (
  id UUID PRIMARY KEY,
  baby_id UUID NOT NULL REFERENCES babies (id) ON DELETE CASCADE,
  enabled BOOLEAN NOT NULL,
  delay_minutes INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS solid_foods (
  id UUID PRIMARY KEY,
  baby_id UUID NOT NULL REFERENCES babies (id) ON DELETE CASCADE,
  food TEXT NOT NULL,
  eaten_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS supplements (
  id UUID PRIMARY KEY,
  baby_id UUID NOT NULL REFERENCES babies (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  given_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS sleep_sessions (
  id UUID PRIMARY KEY,
  baby_id UUID NOT NULL REFERENCES babies (id) ON DELETE CASCADE,
  started_at TIMESTAMPTZ NOT NULL,
  ended_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS temperatures (
  id UUID PRIMARY KEY,
  baby_id UUID NOT NULL REFERENCES babies (id) ON DELETE CASCADE,
  celsius DOUBLE PRECISION NOT NULL,
  measured_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS notes (
  id UUID PRIMARY KEY,
  baby_id UUID NOT NULL REFERENCES babies (id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  noted_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ
);
